plugins {
    id "com.android.application"
}

android {
    namespace "dev.tempera.android.browser"
    compileSdk 35

    defaultConfig {
        applicationId "dev.tempera.android.browser"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "0.1.0-alpha.1"
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ["META-INF/DEPENDENCIES", "META-INF/LICENSE*", "META-INF/NOTICE*"]
        }
    }
}
